Champion League Demo Project: Dialog Class Reference
Dialog Class Reference
#include <dialog.h>
Public Types
enum ETMode { ADD, EDIT, SEARCH }
Public Member Functions
Dialog (QWidget *parent=0)
~Dialog ()
void setMode (ETMode peMode)
void setList (List< Team > &pliga)
void setNode (size_t iPos)
void setId (size_t pId)
Private Slots
void callFunctionTeam ()
void clearAll ()
void searchTeam ()
Private Member Functions
void loadTeam ()
void msgUser (const QString title, const QString message)
void takeTeamFromUi (Team &pTeam)
Private Attributes
Ui::Dialog * ui
List< Team > * liga_
size_t iNodeToEdit_
ETMode eMode_
int idTeam_
Member Enumeration Documentation
enum Dialog::ETMode
Enumerator
ADD
EDIT
SEARCH
Constructor & Destructor Documentation
Dialog::Dialog (QWidget * parent = 0) explicit
References ADD, eMode_, iNodeToEdit_, Ui_Dialog::setupUi(), and ui.
Dialog::~Dialog ()
References ui.
Member Function Documentation
void Dialog::callFunctionTeam () private slot
References iNodeToEdit_, List< T >::insertSorted(), Ui_Dialog::leTeam, liga_, List< T >::modify(), msgUser(), List< T >::searchEleName(), takeTeamFromUi(), and ui.
void Dialog::clearAll () private slot
void Dialog::loadTeam () private
References Team::getDerrotas(), Team::getEmpates(), Team::getGolesAFavor(), Team::getGolesEnContra(), Team::getNombre(), Team::getVictorias(), iNodeToEdit_, Ui_Dialog::leDraws, Ui_Dialog::leGoals, Ui_Dialog::leGoalsA, Ui_Dialog::leLosses, Ui_Dialog::leTeam, Ui_Dialog::leWins, liga_, List< T >::searchPos(), and ui.
Referenced by setNode().
void Dialog::msgUser (const QString title, const QString message) private
Referenced by callFunctionTeam(), and searchTeam().
void Dialog::searchTeam () private slot
References EDIT, liga_, msgUser(), List< T >::searchEleName(), setMode(), setNode(), and takeTeamFromUi().
void Dialog::setId (size_t pId)
void Dialog::setList (List< Team > & pliga)
References liga_.
Referenced by MainWindow::addTeam(), MainWindow::editTeam(), and MainWindow::searchTeam().
void Dialog::setMode (Dialog::ETMode peMode)
References ADD, Ui_Dialog::btnOK, Ui_Dialog::btnSearch, EDIT, eMode_, Ui_Dialog::leTeam, SEARCH, and ui.
Referenced by MainWindow::addTeam(), MainWindow::editTeam(), searchTeam(), and MainWindow::searchTeam().
void Dialog::setNode (size_t iPos)
References iNodeToEdit_, and loadTeam().
Referenced by MainWindow::editTeam(), and searchTeam().
void Dialog::takeTeamFromUi (Team & pTeam) private
References Ui_Dialog::leDraws, Ui_Dialog::leGoals, Ui_Dialog::leGoalsA, Ui_Dialog::leLosses, Ui_Dialog::leTeam, Ui_Dialog::leWins, Team::setDerrotas(), Team::setEmpates(), Team::setGolesAFavor(), Team::setGolesEnContra(), Team::setNombre(), Team::setVictorias(), and ui.
Referenced by callFunctionTeam(), and searchTeam().
Member Data Documentation
ETMode Dialog::eMode_ private
Referenced by Dialog(), and setMode().
int Dialog::idTeam_ private
size_t Dialog::iNodeToEdit_ private
Referenced by callFunctionTeam(), Dialog(), loadTeam(), and setNode().
List<Team>* Dialog::liga_ private
Referenced by callFunctionTeam(), loadTeam(), searchTeam(), and setList().
Ui::Dialog* Dialog::ui private
Referenced by callFunctionTeam(), Dialog(), loadTeam(), setMode(), takeTeamFromUi(), and ~Dialog().
The documentation for this class was generated from the following files:
dialog.h
dialog.cpp