Champion League Demo Project: List< T > Class Template Reference
List< T > Class Template Reference
#include <list.h>
Public Member Functions
List ()
~List ()
bool isEmpty ()
size_t length ()
void insertAfter (T e)
void insert (size_t pos, T e)
T searchPos (size_t pos)
void modify (size_t pos, T e)
void erase (size_t pos)
void copy (List< T > &lNew)
void copySorted (List< T > &lNew)
void sort ()
sort insertion sort
void sortDesc ()
void insertSorted (T e)
size_t searchEleName (T e)
bool readFromFile (const char *fileName)
bool writeToFile (const char *fileName)
bool readFromBinaryFile (const char *fileName)
bool writeToBinaryFile (const char *fileName)
bool readFromBinaryFile2 (const char *fileName)
bool writeToBinaryFile2 (const char *fileName)
std::string toStd ()
Private Member Functions
void init ()
Private Attributes
Node< T > * liga_
size_t lon_
Constructor & Destructor Documentation
template<class T > List< T >::List ()
template<class T > List< T >::~List ()
References Node< T >::next.
Member Function Documentation
template<class T> void List< T >::copy (List< T > & lNew)
References Node< T >::info, List< T >::insertAfter(), and Node< T >::next.
Referenced by MainWindow::openFile().
template<class T> void List< T >::copySorted (List< T > & lNew)
References Node< T >::info, List< T >::insertSorted(), and Node< T >::next.
template<class T > void List< T >::erase (size_t pos)
References Node< T >::next.
Referenced by MainWindow::cleanPlayerList(), MainWindow::deletePlayer(), MainWindow::deleteTeam(), and MainWindow::openFile().
template<class T > void List< T >::init () private
template<class T> void List< T >::insert (size_t pos, T e)
References Node< T >::next.
template<class T> void List< T >::insertAfter (T e)
References Node< T >::next.
Referenced by List< T >::copy().
template<class T> void List< T >::insertSorted (T e)
References Node< T >::info, and Node< T >::next.
Referenced by Dialog2::callFunctionPlayer(), Dialog::callFunctionTeam(), and List< T >::copySorted().
template<class T > bool List< T >::isEmpty ()
Referenced by MainWindow::cleanPlayerList(), MainWindow::deletePlayer(), MainWindow::deleteTeam(), MainWindow::editPlayer(), MainWindow::editTeam(), MainWindow::loadPlayerList(), MainWindow::loadTeamList(), MainWindow::saveAll(), MainWindow::saveAs(), MainWindow::searchPlayer(), MainWindow::searchTeam(), MainWindow::sortPlayerList(), MainWindow::sortPlayerListDesc(), MainWindow::sortTeamList(), and MainWindow::sortTeamListDesc().
template<class T > size_t List< T >::length ()
Referenced by MainWindow::cleanPlayerList(), MainWindow::loadPlayerList(), MainWindow::loadTeamList(), MainWindow::openFile(), MainWindow::saveAll(), and MainWindow::saveAs().
template<class T> void List< T >::modify (size_t pos, T e)
References Node< T >::info, and Node< T >::next.
Referenced by Dialog2::callFunctionPlayer(), and Dialog::callFunctionTeam().
template<class T > bool List< T >::readFromBinaryFile (const char * fileName)
template<class T > bool List< T >::readFromBinaryFile2 (const char * fileName)
Referenced by MainWindow::init(), MainWindow::loadPlayerList(), and MainWindow::openFile().
template<class T > bool List< T >::readFromFile (const char * fileName)
Referenced by MainWindow::init(), MainWindow::loadPlayerList(), and MainWindow::openFile().
template<class T> size_t List< T >::searchEleName (T e)
References Node< T >::info, and Node< T >::next.
Referenced by Dialog::callFunctionTeam(), Dialog2::searchPlayer(), and Dialog::searchTeam().
template<class T > T List< T >::searchPos (size_t pos)
References Node< T >::info, and Node< T >::next.
Referenced by MainWindow::deletePlayerFile(), Dialog2::loadPlayer(), MainWindow::loadPlayerList(), Dialog::loadTeam(), MainWindow::loadTeamList(), MainWindow::saveAs(), and MainWindow::savePlayers().
template<class T > void List< T >::sort ()
sort insertion sort
References Node< T >::info, and Node< T >::next.
Referenced by MainWindow::sortPlayerList(), and MainWindow::sortTeamList().
template<class T > void List< T >::sortDesc ()
References Node< T >::info, and Node< T >::next.
Referenced by MainWindow::sortPlayerListDesc(), and MainWindow::sortTeamListDesc().
template<class T > std::string List< T >::toStd ()
References Node< T >::info, and Node< T >::next.
template<class T > bool List< T >::writeToBinaryFile (const char * fileName)
References Node< T >::info, and Node< T >::next.
template<class T > bool List< T >::writeToBinaryFile2 (const char * fileName)
References Node< T >::info, and Node< T >::next.
Referenced by MainWindow::saveAll(), MainWindow::saveAs(), and MainWindow::savePlayers().
template<class T > bool List< T >::writeToFile (const char * fileName)
References Node< T >::info, and Node< T >::next.
Referenced by MainWindow::saveAll(), MainWindow::saveAs(), and MainWindow::savePlayers().
Member Data Documentation
template<class T> Node<T>* List< T >::liga_ private
template<class T> size_t List< T >::lon_ private
The documentation for this class was generated from the following files:
list.h
list.cpp