Champion League Demo Project: MainWindow Class Reference
MainWindow Class Reference
The MainWindow class.
#include <mainwindow.h>
Public Member Functions
MainWindow (QWidget *parent=0)
MainWindow constructor.
~MainWindow ()
Private Slots
void openFile ()
openFile Open file slot
void sortTeamList ()
sortTeamList sort teams by points
void saveAll ()
saveAll Save all into data files
void saveAs ()
saveAs Save as...
void addTeam ()
addTeam Open dialog in order to add new teams
void editTeam ()
editTeam Edit the selected team
void deleteTeam ()
deleteTeam Delete selected item...
void searchTeam ()
searchTeam Search some item
void loadPlayerList (int iTeamPos)
loadList Load player data from memory to the user interfaz
void sortPlayerList ()
sortPlayerList sort players by goals
void addPlayer ()
addTeam Open dialog in order to add new teams
void editPlayer ()
editTeam Edit the selected team
void deletePlayer ()
deleteTeam Delete selected item...
void searchPlayer ()
searchTeam Search some item
void sortTeamListDesc ()
sortTeamListDesc Reverse sort teams by points
void sortPlayerListDesc ()
sortPlayerListDesc Reverse sort player by goals
Private Member Functions
void init ()
init method
void msgUser (const QString title, const QString message)
General messages pop up.
void loadTeamList ()
loadTeamList Load data from memory to the user interfaz
void cleanPlayerList ()
cleanPlayerList delete actual jugadores_ list
void savePlayers ()
savePlayers save players to the selected team
void deletePlayerFile ()
deletePlayerFile delete actual player's file
Private Attributes
Ui::MainWindow * ui
List< Team > liga_
liga_ Team's dynamic list
List< Player > jugadores_
jugadores_ Player's dynamic list
QString qsDataFile_
qsDataFile_ Team's Data file
QString qsDataFilePlayer_
qsDataFilePlayer_ Player's Data file
size_t iSelectedTeam_
iSelectedTeam_ Selected team
Detailed Description
The MainWindow class.
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget * parent = 0) explicit
MainWindow constructor.
Parameters
parent
References init(), and ui.
MainWindow::~MainWindow ()
References ui.
Member Function Documentation
void MainWindow::addPlayer () private slot
addTeam Open dialog in order to add new teams
References Dialog2::ADD, iSelectedTeam_, jugadores_, loadPlayerList(), savePlayers(), Dialog2::setList(), and Dialog2::setMode().
void MainWindow::addTeam () private slot
addTeam Open dialog in order to add new teams
References Dialog::ADD, liga_, loadTeamList(), saveAll(), Dialog::setList(), and Dialog::setMode().
void MainWindow::cleanPlayerList () private
cleanPlayerList delete actual jugadores_ list
References List< T >::erase(), List< T >::isEmpty(), jugadores_, and List< T >::length().
Referenced by deleteTeam(), and loadPlayerList().
void MainWindow::deletePlayer () private slot
deleteTeam Delete selected item...
slot function
References List< T >::erase(), iSelectedTeam_, List< T >::isEmpty(), jugadores_, loadPlayerList(), msgUser(), savePlayers(), and ui.
void MainWindow::deletePlayerFile () private
deletePlayerFile delete actual player's file
References DEFAULT_DATA_FILE_EXT, Team::getNombre(), iSelectedTeam_, liga_, qsDataFilePlayer_, and List< T >::searchPos().
Referenced by deleteTeam().
void MainWindow::deleteTeam () private slot
deleteTeam Delete selected item...
slot function
References cleanPlayerList(), deletePlayerFile(), List< T >::erase(), iSelectedTeam_, List< T >::isEmpty(), liga_, loadTeamList(), msgUser(), and saveAll().
void MainWindow::editPlayer () private slot
editTeam Edit the selected team
References Dialog2::EDIT, iSelectedTeam_, List< T >::isEmpty(), jugadores_, loadPlayerList(), msgUser(), savePlayers(), Dialog2::setList(), Dialog2::setMode(), Dialog2::setNode(), and ui.
void MainWindow::editTeam () private slot
editTeam Edit the selected team
References Dialog::EDIT, iSelectedTeam_, List< T >::isEmpty(), liga_, loadTeamList(), msgUser(), saveAll(), Dialog::setList(), Dialog::setMode(), and Dialog::setNode().
void MainWindow::init () private
init method
References BINARY_FILE, DEFAULT_DATA_DIR, DEFAULT_DATA_FILE_EXT, DEFAULT_DATA_PLAYER_FILE, DEFAULT_DATA_TEAM_FILE, iSelectedTeam_, liga_, loadTeamList(), qsDataFile_, qsDataFilePlayer_, List< T >::readFromBinaryFile2(), and List< T >::readFromFile().
Referenced by MainWindow().
void MainWindow::loadPlayerList (int iTeamPos) private slot
loadList Load player data from memory to the user interfaz
References BINARY_FILE, cleanPlayerList(), DEFAULT_DATA_FILE_EXT, Team::getNombre(), iSelectedTeam_, List< T >::isEmpty(), jugadores_, List< T >::length(), liga_, qsDataFilePlayer_, List< T >::readFromBinaryFile2(), List< T >::readFromFile(), List< T >::searchPos(), Player::toStd(), and ui.
Referenced by addPlayer(), deletePlayer(), editPlayer(), saveAll(), saveAs(), searchPlayer(), sortPlayerList(), and sortPlayerListDesc().
void MainWindow::loadTeamList () private
loadTeamList Load data from memory to the user interfaz
References List< T >::isEmpty(), List< T >::length(), liga_, List< T >::searchPos(), Team::toStd(), and ui.
Referenced by addTeam(), deleteTeam(), editTeam(), init(), openFile(), searchTeam(), sortTeamList(), and sortTeamListDesc().
void MainWindow::msgUser (const QString title, const QString message) private
General messages pop up.
Parameters
title
message
Referenced by deletePlayer(), deleteTeam(), editPlayer(), editTeam(), openFile(), saveAll(), saveAs(), savePlayers(), searchPlayer(), searchTeam(), sortPlayerList(), sortPlayerListDesc(), sortTeamList(), and sortTeamListDesc().
void MainWindow::openFile () private slot
openFile Open file slot
References BINARY_FILE, List< T >::copy(), DEFAULT_DATA_DIR, DEFAULT_DATA_PLAYER_FILE, List< T >::erase(), List< T >::length(), liga_, loadTeamList(), msgUser(), qsDataFile_, qsDataFilePlayer_, List< T >::readFromBinaryFile2(), and List< T >::readFromFile().
void MainWindow::saveAll () private slot
saveAll Save all into data files
References BINARY_FILE, iSelectedTeam_, List< T >::isEmpty(), List< T >::length(), liga_, loadPlayerList(), msgUser(), qsDataFile_, savePlayers(), ui, List< T >::writeToBinaryFile2(), and List< T >::writeToFile().
Referenced by addTeam(), deleteTeam(), editTeam(), and searchTeam().
void MainWindow::saveAs () private slot
saveAs Save as...
slot function
References BINARY_FILE, DEFAULT_DATA_DIR, DEFAULT_DATA_FILE_EXT, DEFAULT_DATA_PLAYER_FILE, Team::getNombre(), List< T >::isEmpty(), jugadores_, List< T >::length(), liga_, loadPlayerList(), msgUser(), qsDataFile_, qsDataFilePlayer_, List< T >::searchPos(), ui, List< T >::writeToBinaryFile2(), and List< T >::writeToFile().
void MainWindow::savePlayers () private
savePlayers save players to the selected team
References BINARY_FILE, DEFAULT_DATA_FILE_EXT, Team::getNombre(), iSelectedTeam_, jugadores_, liga_, msgUser(), qsDataFilePlayer_, List< T >::searchPos(), List< T >::writeToBinaryFile2(), and List< T >::writeToFile().
Referenced by addPlayer(), deletePlayer(), editPlayer(), saveAll(), searchPlayer(), sortPlayerList(), and sortPlayerListDesc().
void MainWindow::searchPlayer () private slot
searchTeam Search some item
References iSelectedTeam_, List< T >::isEmpty(), jugadores_, loadPlayerList(), msgUser(), savePlayers(), Dialog2::SEARCH, Dialog2::setList(), and Dialog2::setMode().
void MainWindow::searchTeam () private slot
searchTeam Search some item
References List< T >::isEmpty(), liga_, loadTeamList(), msgUser(), saveAll(), Dialog::SEARCH, Dialog::setList(), and Dialog::setMode().
void MainWindow::sortPlayerList () private slot
sortPlayerList sort players by goals
References iSelectedTeam_, List< T >::isEmpty(), jugadores_, loadPlayerList(), msgUser(), savePlayers(), and List< T >::sort().
void MainWindow::sortPlayerListDesc () private slot
sortPlayerListDesc Reverse sort player by goals
References iSelectedTeam_, List< T >::isEmpty(), jugadores_, loadPlayerList(), msgUser(), savePlayers(), and List< T >::sortDesc().
void MainWindow::sortTeamList () private slot
sortTeamList sort teams by points
References List< T >::isEmpty(), liga_, loadTeamList(), msgUser(), and List< T >::sort().
void MainWindow::sortTeamListDesc () private slot
sortTeamListDesc Reverse sort teams by points
References List< T >::isEmpty(), liga_, loadTeamList(), msgUser(), and List< T >::sortDesc().
Member Data Documentation
size_t MainWindow::iSelectedTeam_ private
iSelectedTeam_ Selected team
Referenced by addPlayer(), deletePlayer(), deletePlayerFile(), deleteTeam(), editPlayer(), editTeam(), init(), loadPlayerList(), saveAll(), savePlayers(), searchPlayer(), sortPlayerList(), and sortPlayerListDesc().
List<Player> MainWindow::jugadores_ private
jugadores_ Player's dynamic list
Referenced by addPlayer(), cleanPlayerList(), deletePlayer(), editPlayer(), loadPlayerList(), saveAs(), savePlayers(), searchPlayer(), sortPlayerList(), and sortPlayerListDesc().
List<Team> MainWindow::liga_ private
liga_ Team's dynamic list
Referenced by addTeam(), deletePlayerFile(), deleteTeam(), editTeam(), init(), loadPlayerList(), loadTeamList(), openFile(), saveAll(), saveAs(), savePlayers(), searchTeam(), sortTeamList(), and sortTeamListDesc().
QString MainWindow::qsDataFile_ private
qsDataFile_ Team's Data file
Referenced by init(), openFile(), saveAll(), and saveAs().
QString MainWindow::qsDataFilePlayer_ private
qsDataFilePlayer_ Player's Data file
Referenced by deletePlayerFile(), init(), loadPlayerList(), openFile(), saveAs(), and savePlayers().
Ui::MainWindow* MainWindow::ui private
Referenced by deletePlayer(), editPlayer(), loadPlayerList(), loadTeamList(), MainWindow(), saveAll(), saveAs(), and ~MainWindow().
The documentation for this class was generated from the following files:
mainwindow.h
mainwindow.cpp