Champion League Demo Project: Dialog2 Class Reference
Dialog2 Class Reference
#include <dialog2.h>
Public Types
enum ETMode { ADD, EDIT, SEARCH }
Public Member Functions
Dialog2 (QWidget *parent=0)
~Dialog2 ()
void setMode (ETMode peMode)
void setList (List< Player > &pjugadores)
void setNode (size_t iPos)
Private Slots
void callFunctionPlayer ()
void clearAll ()
void searchPlayer ()
Private Member Functions
void loadPlayer ()
void msgUser (const QString title, const QString message)
void takePlayerFromUi (Player &pPlayer)
Private Attributes
Ui::Dialog2 * ui
List< Player > * jugadores_
size_t iNodeToEdit_
ETMode eMode_
Member Enumeration Documentation
enum Dialog2::ETMode
Enumerator
ADD
EDIT
SEARCH
Constructor & Destructor Documentation
Dialog2::Dialog2 (QWidget * parent = 0) explicit
References ADD, eMode_, iNodeToEdit_, and ui.
Dialog2::~Dialog2 ()
References ui.
Member Function Documentation
void Dialog2::callFunctionPlayer () private slot
References iNodeToEdit_, List< T >::insertSorted(), jugadores_, List< T >::modify(), msgUser(), takePlayerFromUi(), and ui.
void Dialog2::clearAll () private slot
void Dialog2::loadPlayer () private
References Player::getNGoles(), Player::getNombre(), iNodeToEdit_, jugadores_, List< T >::searchPos(), and ui.
Referenced by setNode().
void Dialog2::msgUser (const QString title, const QString message) private
Referenced by callFunctionPlayer(), and searchPlayer().
void Dialog2::searchPlayer () private slot
References EDIT, jugadores_, msgUser(), List< T >::searchEleName(), setMode(), setNode(), and takePlayerFromUi().
void Dialog2::setList (List< Player > & pjugadores)
References jugadores_.
Referenced by MainWindow::addPlayer(), MainWindow::editPlayer(), and MainWindow::searchPlayer().
void Dialog2::setMode (Dialog2::ETMode peMode)
References ADD, EDIT, eMode_, SEARCH, and ui.
Referenced by MainWindow::addPlayer(), MainWindow::editPlayer(), searchPlayer(), and MainWindow::searchPlayer().
void Dialog2::setNode (size_t iPos)
References iNodeToEdit_, and loadPlayer().
Referenced by MainWindow::editPlayer(), and searchPlayer().
void Dialog2::takePlayerFromUi (Player & pPlayer) private
References Player::setNGoles(), Player::setNombre(), and ui.
Referenced by callFunctionPlayer(), and searchPlayer().
Member Data Documentation
ETMode Dialog2::eMode_ private
Referenced by Dialog2(), and setMode().
size_t Dialog2::iNodeToEdit_ private
Referenced by callFunctionPlayer(), Dialog2(), loadPlayer(), and setNode().
List<Player>* Dialog2::jugadores_ private
Referenced by callFunctionPlayer(), loadPlayer(), searchPlayer(), and setList().
Ui::Dialog2* Dialog2::ui private
Referenced by callFunctionPlayer(), Dialog2(), loadPlayer(), setMode(), takePlayerFromUi(), and ~Dialog2().
The documentation for this class was generated from the following files:
dialog2.h
dialog2.cpp