Champion League Demo Project: Ui_MainWindow Class Reference
Ui_MainWindow Class Reference
#include <ui_mainwindow.h>
Public Member Functions
void setupUi (QMainWindow *MainWindow)
void retranslateUi (QMainWindow *MainWindow)
Public Attributes
QAction * actionOpen
QAction * actionSalir
QAction * actionSaveAs
QAction * actionAddTeam
QAction * actionSearchByName
QAction * actionSortByPoints
QAction * actionSave
QAction * actionSortByGoals
QAction * actionAddPlayer
QAction * actionInvertTeamSort
QAction * actionInvertPlayerSort
QAction * actionOpen_Binary
QAction * actionSave_All_B_inary
QWidget * centralWidget
QGridLayout * gridLayout_2
QGridLayout * gridLayout
QListWidget * lstwPlayer
QHBoxLayout * horizontalLayout_2
QPushButton * btnSortPlayer
QPushButton * btnAddPlayer
QPushButton * btnEditPlayer
QPushButton * btnDeletePlayer
QPushButton * btnSearchTeam_2
QHBoxLayout * horizontalLayout
QPushButton * btnSortTeam
QPushButton * btnAddTeam
QPushButton * btnEditTeam
QPushButton * btnDeleteTeam
QPushButton * btnSearchTeam
QListWidget * lstwTeam
QMenuBar * menuBar
QMenu * menu_File
QMenu * menu_Options
QMenu * menu_Players
QToolBar * mainToolBar
QStatusBar * statusBar
Member Function Documentation
void Ui_MainWindow::retranslateUi (QMainWindow * MainWindow) inline
Referenced by setupUi().
void Ui_MainWindow::setupUi (QMainWindow * MainWindow) inline
References retranslateUi().
Referenced by MainWindow::MainWindow().
Member Data Documentation
QAction* Ui_MainWindow::actionAddPlayer
QAction* Ui_MainWindow::actionAddTeam
QAction* Ui_MainWindow::actionInvertPlayerSort
QAction* Ui_MainWindow::actionInvertTeamSort
QAction* Ui_MainWindow::actionOpen
QAction* Ui_MainWindow::actionOpen_Binary
QAction* Ui_MainWindow::actionSalir
QAction* Ui_MainWindow::actionSave
QAction* Ui_MainWindow::actionSave_All_B_inary
QAction* Ui_MainWindow::actionSaveAs
QAction* Ui_MainWindow::actionSearchByName
QAction* Ui_MainWindow::actionSortByGoals
QAction* Ui_MainWindow::actionSortByPoints
QPushButton* Ui_MainWindow::btnAddPlayer
QPushButton* Ui_MainWindow::btnAddTeam
QPushButton* Ui_MainWindow::btnDeletePlayer
QPushButton* Ui_MainWindow::btnDeleteTeam
QPushButton* Ui_MainWindow::btnEditPlayer
QPushButton* Ui_MainWindow::btnEditTeam
QPushButton* Ui_MainWindow::btnSearchTeam
QPushButton* Ui_MainWindow::btnSearchTeam_2
QPushButton* Ui_MainWindow::btnSortPlayer
QPushButton* Ui_MainWindow::btnSortTeam
QWidget* Ui_MainWindow::centralWidget
QGridLayout* Ui_MainWindow::gridLayout
QGridLayout* Ui_MainWindow::gridLayout_2
QHBoxLayout* Ui_MainWindow::horizontalLayout
QHBoxLayout* Ui_MainWindow::horizontalLayout_2
QListWidget* Ui_MainWindow::lstwPlayer
Referenced by MainWindow::deletePlayer(), MainWindow::editPlayer(), and MainWindow::loadPlayerList().
QListWidget* Ui_MainWindow::lstwTeam
Referenced by MainWindow::loadTeamList(), MainWindow::saveAll(), and MainWindow::saveAs().
QToolBar* Ui_MainWindow::mainToolBar
QMenu* Ui_MainWindow::menu_File
QMenu* Ui_MainWindow::menu_Options
QMenu* Ui_MainWindow::menu_Players
QMenuBar* Ui_MainWindow::menuBar
QStatusBar* Ui_MainWindow::statusBar
The documentation for this class was generated from the following file:
ui_mainwindow.h